# version: "3.8"
services:
  dev-https-portal:
    image: steveltn/https-portal:latest
    container_name: DevHttpsPortal
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "defender-portal.duckdns.org -> http://dev-portal:80"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

  dev-identity-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.IdentityService
    image: dev-identity-service
    container_name: DevIdentityService
    ports:
      - "49050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-user-management-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.UserManagementService
    image: dev-user-management-service
    container_name: DevUserManagementService
    ports:
      - "49051:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-notification-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.NotificationService
    image: dev-notification-service
    container_name: DevNotificationService
    ports:
      - "49052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-portal:
    build:
      context: .
      dockerfile: Dockerfiles/Portal_Dockerfile
      args:
        SERVICE_DIR: Defender.Portal
    image: dev-portal
    container_name: DevPortal
    ports:
      - "49053:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-wallet-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.WalletService
    image: dev-wallet-service
    container_name: DevWalletService
    ports:
      - "49058:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-risk-games-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.RiskGamesService
    image: dev-risk-games-service
    container_name: DevRiskGamesService
    ports:
      - "49060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-budget-tracker-service:
    build:
      context: .
      dockerfile: Dockerfiles/Service_Dockerfile
      args:
        SERVICE_DIR: Defender.BudgetTracker
    image: dev-budget-tracker-service
    container_name: DevBudgetTrackerService
    ports:
      - "49061:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

volumes:
  https-portal-data:
