# version: "3.8"
services:
  # As I have issues with DNS from cloudflare I will use http as of now
  dev-https-portal:
    image: steveltn/https-portal:latest
    container_name: DevHttpsPortal
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "defender-portal.coded-by-danil.dev -> http://dev-portal:80"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  dev-identity-service:
    image: defendersd/dev-identity-service
    container_name: DevIdentityService
    ports:
      - "49050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-user-management-service:
    image: defendersd/dev-user-management-service
    container_name: DevUserManagementService
    ports:
      - "49051:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-notification-service:
    image: defendersd/dev-notification-service
    container_name: DevNotificationService
    ports:
      - "49052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-portal:
    image: defendersd/dev-portal
    container_name: DevPortal
    ports:
      - "49053:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-wallet-service:
    image: defendersd/dev-wallet-service
    container_name: DevWalletService
    ports:
      - "49058:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-risk-games-service:
    image: defendersd/dev-risk-games-service
    container_name: DevRiskGamesService
    ports:
      - "49060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

  dev-budget-tracker-service:
    image: defendersd/dev-budget-tracker-service
    container_name: DevBudgetTrackerService
    ports:
      - "49061:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list

volumes:
  https-portal-data:
