# version: "3.8"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
    restart: always

  dev-identity-service:
    image: defendersd/dev-identity-service
    container_name: DevIdentityService
    ports:
      - "49050:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-user-management-service:
    image: defendersd/dev-user-management-service
    container_name: DevUserManagementService
    ports:
      - "49051:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-notification-service:
    image: defendersd/dev-notification-service
    container_name: DevNotificationService
    ports:
      - "49052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-portal:
    image: defendersd/dev-portal
    container_name: DevPortal
    ports:
      - "49053:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-wallet-service:
    image: defendersd/dev-wallet-service
    container_name: DevWalletService
    ports:
      - "49058:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-risk-games-service:
    image: defendersd/dev-risk-games-service
    container_name: DevRiskGamesService
    ports:
      - "49060:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31

  dev-budget-tracker-service:
    image: defendersd/dev-budget-tracker-service
    container_name: DevBudgetTrackerService
    ports:
      - "49061:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev
    env_file:
      - secrets/secrets.dev.list
    restart: always
    dns:
      - 192.168.0.31
