services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300

  nginx-proxy:
    image: defendersd/nginx-reverse-proxy:latest
    container_name: nginx-proxy
    network_mode: host
